# -*- coding: utf-8 -*-

"""
SSD1306 CONSTS
"""
# Commands
SET_CONTRAST_CONTROL = 0x81
SET_ENTIRE_DISPLAY_ON = 0xA5
SET_ENTIRE_DISPLAY_NORMAL = 0xA4
SET_DIRECT_DISPLAY = 0xA6
SET_INVERSE_DISPLAY = 0xA7
SET_DISPLAY_OFF = 0xAE
SET_DISPLAY_ON = 0xAF
SET_CONTINUOUS_RIGHT_HORIZONAL_SCROLL = 0x26
SET_CONTINUOUS_LEFT_HORIZONAL_SCROLL = 0x27
SET_CONTINUOUS_VERTICAL_AND_RIGHT_HORIZONAL_SCROLL = 0x29
SET_CONTINUOUS_VERTICAL_AND_LEFT_HORIZONAL_SCROLL = 0x2A
SET_CONTINUOUS_SCROLL_STOP = 0x2E
SET_CONTINUOUS_SCROLL_START = 0x2F
SET_VERTICAL_SCROLL_AREA = 0xA3
SET_LOWER_COLUMN_START_ADDRESS_FOR_PAGE_ADDRESSING_MODE = lambda x: (x & 0x0F)
SET_HIGHER_COLUMN_START_ADDRESS_FOR_PAGE_ADDRESSING_MODE = lambda x: ((x & 0x0F) | 0x10)
SET_MEMORY_ADDRESSING_MODE = 0x20
SET_COLUMN_ADDRESS = 0x21
SET_PAGE_ADDRESS = 0x22
SET_PAGE_START_ADDRESS_FOR_PAGE_ADDRESSING_MODE = lambda x: ((x & 0x07) | 0xB0)
SET_DISPLAY_START_LINE = lambda x: ((x & 0x3F) | 0x40)
SET_SEGMENT_RE_MAP_0 = 0xA0
SET_SEGMENT_RE_MAP_127 = 0xA1
SET_MULTIPLEX_RATIO = 0xA8
SET_COM_OUTPUT_SCAN_DIRECTION_DIRECT = 0xC0
SET_COM_OUTPUT_SCAN_DIRECTION_INVERSE = 0xC8
SET_DISPLAY_OFFSET = 0xD3
SET_COM_PINS_HARDWARE_CONFIGURATION = 0xDA
SET_DISPLAY_CLOCK_DIVIDE_RATIO_OSCILLATOR_FREQUENCY = 0xD5
SET_PRE_CHARGE_PERIOD = 0xD9
SET_VCOMH_DESELECT_LEVEL = 0xDB
NOP = 0xE3

# Pages
Page0 = 0x00
Page1 = 0x01
Page2 = 0x02
Page3 = 0x03
Page4 = 0x04
Page5 = 0x05
Page6 = 0x06
Page7 = 0x07

# FrameFrequency
Frames5 = 0x00
Frames64 = 0x01
Frames128 = 0x02
Frames256 = 0x03
Frames3 = 0x04
Frames4 = 0x05
Frames25 = 0x06
Frames2 = 0x07

# MemoryAddressMode
HorizontalAddressingMode = 0x00
VerticalAddressingMode = 0x01
PageAddressingMode = 0x02

# ComPinsHardwareConfiguration
SequentialComPin_DisabledComLeftRightRemap = 0x02
SequentialComPin_EnableComLeftRightRemap = 0x22
AlternativeComPin_DisabledComLeftRightRemap = 0x12
AlternativeComPin_EnableComLeftRightRemap = 0x32

# VcomhDeselectLevel
VccDot65Times = 0x00
VccDot77Times = 0x20
VccDot83Times = 0x30

